name: languages

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  languages:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup git
      run: |
        git config --global user.email "example@example.com"
        git config --global user.name "Example"
        git remote add upstream https://github.com/spack/spack.git
        git fetch upstream
        git checkout -b languages upstream/develop
    - run: |
        echo "Hello, world!" > languages.txt
        git add languages.txt
        git commit -m "Add languages.txt"
        git push origin -f languages

