name: languages

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  languages:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: set up python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: configure git
      run: |
        git config --global user.email "example@example.com"
        git config --global user.name "Example"
        git checkout -b languages
    - run: |
        . spack/share/spack/setup-env.sh
        spack-python update_languages.py
    - run: |
        git -C spack diff > language.patch
        git add language.patch
        git commit -m "language patch"
        git push -f origin languages
