name: languages

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  languages:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: configure git
      run: |
        git config --global user.email "example@example.com"
        git config --global user.name "Example"
    - name: checkout spack
      uses: actions/checkout@v4
      with:
        repository: spack/spack
        ref: develop
        path: spack
    - name: set up python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - run: |
        . spack/share/spack/setup-env.sh
        spack-python update_languages.py zstd
    - run: |
        git checkout -b languages
        git -C spack format-patch -1
        git add .
        git commit -m "language patch"
        git push -f origin languages
